### ISSUE TITLE
Add support for wrapped secret id in EnvironmentVaultConfiguration.appRoleAuthentication()

### ISSUE THREAD

**Issue by mdeknowis** [spring-projects/spring-vault#379]
With #165 Spring Vault supports wrapped Secrets. But currently the `EnvironmentVaultConfiguration.appRoleAuthentication()` does not allow to configure them, so it's only possible to to define an unwrapped secret id like

```yaml
spring:
  vault:
    uri: "http://vault"
    authentication: "APPROLE"
    app-role:
      role-id: "81c0935e-61ba-d30a-8811-a181967bbc52"
      secret-id: "a364bb91-9d6c-4a99-7b1e-ce6ce5bc08ce"
```

But it would be a great help, if wrapped secret ids would be also added to native support there like:

```yaml
spring:
  vault:
    uri: "http://vault"
    authentication: "APPROLE"
    app-role:
      role-id: "81c0935e-61ba-d30a-8811-a181967bbc52"
      wrapped-secret-id: "s.qF4GKDfnL0yibtzWdpTH3cVB"
```

I assume the change would be in `org.springframework.vault.config.EnvironmentVaultConfiguration.appRoleAuthentication()` to check for `wrapped-secret-id`, if `secret-id` is `null` and use `SecretId.wrapped(VaultToken.of("…"))` like

```java
protected ClientAuthentication appRoleAuthentication() {

    String roleId = getProperty("vault.app-role.role-id");
    String secretId = getProperty("vault.app-role.secret-id");
    String wappredSecretId = getProperty("vault.app-role.wrapped-secret-id"); // <- new
    Assert.hasText(roleId,
            "Vault AppRole authentication: RoleId (vault.app-role.role-id) must not be empty");

    AppRoleAuthenticationOptions.AppRoleAuthenticationOptionsBuilder builder = AppRoleAuthenticationOptions
            .builder().roleId(roleId);

    if (StringUtils.hasText(secretId)) {
        builder = builder.secretId(secretId);
    } else if (StringUtils.hasText(wappredSecretId )) { // <- new
        builder = builder.secretId(SecretId.wrapped(VaultToken.of(wappredSecretId ))); // <- new
    }

    return new AppRoleAuthentication(builder.build(), restOperations());
}
```
