### ISSUE TITLE
VMSS support for Azure MSI Authentication

### ISSUE THREAD

**Issue by whiskeysierra** [spring-projects/spring-vault#614]
The *Vault Plugin: Azure Auth Backend* has support for both, standalone VMs and VM scale sets (VMSS):

> * `vm_name (string: "")` - The virtual machine name for the machine that generated the MSI token. This information can be obtained through instance metadata. If vmss_name is provided, this value is ignored.
> * `vmss_name (string: "")` - The virtual machine scale set name for the machine that generated the MSI token. This information can be obtained through instance metadata.
>
> https://www.vaultproject.io/api-docs/auth/azure#login

Spring Vault only supports standalone VMs right now, i.e. it will always set the `vm_name` property when sending a login request.

The `/metadata/instance` request will return a scale set name, if the VM is part of a scale set:

```yaml
{
  "name": "myScaleSet_0",
  "vmScaleSetName": "myScaleSet",
  # ..
}
```

Standalone VMs, which are not part of a scale set, have an empty scale set name:

```yaml
{
  "name": "myVm",
  "vmScaleSetName": "",
  # ..
}
```

## Implementation notes

- `AzureVmEnvironment` should hold an additional property: `String vmssName`
- `AzureMsiAuthentication#toAzureVmEnvironment` should:
  - read `vmScaleSetName`
  - set `vm_name` if `vmScaleSetName` is empty
  - set `vmss_name` otherwise
