### ISSUE TITLE
Azure MSI auth to use with reactive infra

### ISSUE THREAD

**Issue by nks0203** [spring-projects/spring-vault#665]
**Is your feature request related to a problem? Please describe.**

I am trying to use Azure MSI auth with spring webflux project . It gives me the following error :

**_Cannot construct vaultTokenSupplier from org.springframework.vault.authentication.AzureMsiAuthentication : ClientAuthentication must implement AuthenticationStepsFactory or be TokenAuthentication_**

**Describe the solution you'd like**

The other counterpart - Aws , Approle authentication classes implements AuthenticationStepsFactory but not AzureMsi Authentication.

Due to this it throws the above exception in VaultReactiveConfiguration.createVaultTokenSupplier() method.

If we can have AuthenticationStepsFactory  interface implemented in AzureMsiAuthentication.java . It would work.

**Describe alternatives you've considered**

Using bootstrap loader without spring.config.import property

**failing setup**
Spring boot - 2.5.4
spring-cloud-dependencies- 2020.0.3

**application.yml**
-- **Please ignore the indentation**
```
spring:
   application:
       name: app
   config:
        import: vault://
   cloud:
      vault:
	  reactive:
	      enabled: false
	  uri: //my vaulturi
          kv:
            enabled: true
            backend: backend
            default-context: context
	  authentication: azure_msi
	  azure_msi:
		role: azure_role
		metadata-service: //url
		isntance-token-service: //url

```

I have tried with removing spring.config.import property , in this case the azure login steps are not even executed.
Please help.
