### ISSUE TITLE
data being added in path of KV1 Engine, but not for KV2

### ISSUE THREAD

**Issue by ChrisJBurns** [spring-projects/spring-vault#738]
We are using version `2.1.3.RELEASE` version of `spring-cloud-starter-vault-config` and for some reason we are getting issues when connecting to V2 KV Secret Engines.

I can confirm that when we point our config to a secret engine that is V1, the `/data/` path is inserted and used when trying to retrieve values. But when we switch to V2, the `/data/` path isn't inserted.

Is there some kind of reverse logic somewhere? We aren't doing anything special as far as I can see. 

### Bootstrap Config
```yaml
spring:
  cloud:
    vault:
      kv:
        enabled: true
      uri: [REDACTED]
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: [REDACTED]
      config:
        order: -10
```
