### ISSUE TITLE
Spring Vault Github Token Authentication method request

### ISSUE THREAD

**Issue by radhakrishna67** [spring-projects/spring-vault#821]
Hi team,
               we are allowed to use only GitHub token to login into HashiCorp Vault. Spring Vault is currently not supporting GitHub token authentication method. 
Could you please consider this as an enhancement ?

Thanks,
Radhakrishna.

**Comment by mp911de** [comment]
Right now, you're the first one who asked. Spring Vault comes with an extensible model so for the time being, feel free to implement your own `ClientAuthentication` based on GitHub tokens.

**Comment by ENate** [comment]
Hi All. I am trying to set up a distributed spring boot application using Hashicorp vault to save lots of secrets. And trying to use spring cloud config to import those secrets into my spring application. Unfortunately, when I use ```spring.config.import= vault:// ```, it tells me that tthe application cannot load data from ``` vault:// ```  with the following error:
```
java.lang.IllegalStateException: Unable to load config data from 'vault://secret/application'
```
. I have spent hours trying to use the implementation I found in the docs but it cannot work. My configuration for spring vault in the properties file for spring cloud config is as follows:

```

spring:
    
    profiles:
        active: native, vault
    # security config
    data:
        mongodb:
            uri: mongodb+srv://${DB_NAME}:${DB_PASS}@mongo-atlas

    # application name
    application:
        name: config-server
    cloud:
        
        vault:
            enabled: true
            kv:
                enabled: true
                backend: secrets
        config:
        
            server:
                vault:
                    enabled: true
                    host: 127.0.0.1
                    scheme: http
                    port: 8200
                    uri: http://localhost:8200
                    token: <root token generated from vault docker -dev>
                    order: 1
                native:
                    // added more properties
                    order: 2
```
I am using spring cloud 2023 (with spring vault 4.ü+ I guess)- spring boot 3.2.1. Any help will be appreciated.
